version: '3.8'
services:
  web-service:
    build: ./src
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
    depends_on:
      - service-db
    extra_hosts:
    - "frontend.test.com:127.0.0.1"
    - "admin.test.com:127.0.0.1"
    environment:
      - MYSQL_HOSTNAME=service-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vcs2
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password

  service-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root